# Generated by Django 2.2.7 on 2019-11-22 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_auto_20191121_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='analysis',
            field=models.CharField(default=-1, max_length=6),
            preserve_default=False,
        ),
    ]
