# Generated by Django 2.2.7 on 2019-11-22 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_comment_analysis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='data',
            field=models.IntegerField(max_length=100000),
        ),
    ]
