# Generated by Django 2.2.7 on 2019-11-22 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_auto_20191122_0712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='data',
            field=models.IntegerField(),
        ),
    ]
