# Generated by Django 2.2.7 on 2019-11-22 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_auto_20191122_0713'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='data',
            new_name='data_id',
        ),
    ]
